<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.40">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="John D. Coady">
<meta name="dcterms.date" content="2026-10-04">
<meta name="description" content="A plain-language tour of a Zenodo preprint on a 2×2 Hermitian-matrix model of (1+3)D spacetime over F_p, with exact finite-field checks.">

<title>Spacetime in 2×2 Matrices over a Finite Field – John Coady’s Blog</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-549806ee2085284f45b00abea8c6df48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-fe7872a82928c9cb84149cb81cc2feaf.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">John Coady’s Blog</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">All Posts</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../math.html"> 
<span class="menu-text">Pure Mathematics</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../physics.html"> 
<span class="menu-text">Math Physics</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://orcid.org/0009-0008-6020-5733"> 
<span class="menu-text"><img src="https://upload.wikimedia.org/wikipedia/commons/0/06/ORCID_iD.svg" alt="ORCID iD" style="height:20px; width:20px; vertical-align:-3px;"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://x.com/johndavidcoady"> <i class="bi bi-twitter-x" role="img" aria-label="X">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/jcoady"> <i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Spacetime in 2×2 Matrices over a Finite Field</h1>
            <p class="subtitle lead">How a Galois extension sidesteps a Witt-index obstruction, fixes a composition anomaly, and gives a small, checkable model of Lorentz holonomy</p>
                  <div>
        <div class="description">
          A plain-language tour of a Zenodo preprint on a 2×2 Hermitian-matrix model of (1+3)D spacetime over F_p, with exact finite-field checks.
        </div>
      </div>
                          <div class="quarto-categories">
                <div class="quarto-category">pure-math</div>
                <div class="quarto-category">geometry</div>
                <div class="quarto-category">hyperbolic-geometry</div>
                <div class="quarto-category">mathematical-physics</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>John D. Coady </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">October 4, 2026</p>
      </div>
    </div>
    
      
      <div>
      <div class="quarto-title-meta-heading">Doi</div>
      <div class="quarto-title-meta-contents">
        <p class="doi">
          <a href="https://doi.org/10.5281/zenodo.23138782">10.5281/zenodo.23138782</a>
        </p>
      </div>
    </div>
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul class="collapse">
  <li><a href="#the-one-paragraph-version" id="toc-the-one-paragraph-version" class="nav-link active" data-scroll-target="#the-one-paragraph-version">The one-paragraph version</a></li>
  <li><a href="#why-bother-with-finite-fields" id="toc-why-bother-with-finite-fields" class="nav-link" data-scroll-target="#why-bother-with-finite-fields">Why bother with finite fields?</a></li>
  <li><a href="#the-obstruction-and-why-it-is-not-one" id="toc-the-obstruction-and-why-it-is-not-one" class="nav-link" data-scroll-target="#the-obstruction-and-why-it-is-not-one">The obstruction, and why it is not one</a></li>
  <li><a href="#rotors-all-of-so13mathbbf_p-from-eight-numbers" id="toc-rotors-all-of-so13mathbbf_p-from-eight-numbers" class="nav-link" data-scroll-target="#rotors-all-of-so13mathbbf_p-from-eight-numbers">Rotors: all of <span class="math inline">\(SO(1,3;\mathbb{F}_p)\)</span> from eight numbers</a></li>
  <li><a href="#reading-off-a-generator-the-anchor-formula" id="toc-reading-off-a-generator-the-anchor-formula" class="nav-link" data-scroll-target="#reading-off-a-generator-the-anchor-formula">Reading off a generator: the anchor formula</a></li>
  <li><a href="#the-anchor-doubling-law-and-the-11-mystery" id="toc-the-anchor-doubling-law-and-the-11-mystery" class="nav-link" data-scroll-target="#the-anchor-doubling-law-and-the-11-mystery">The “anchor doubling” law and the 11% mystery</a></li>
  <li><a href="#edge-transports-and-holonomy" id="toc-edge-transports-and-holonomy" class="nav-link" data-scroll-target="#edge-transports-and-holonomy">Edge transports and holonomy</a></li>
  <li><a href="#ghost-parity-and-the-quadrume" id="toc-ghost-parity-and-the-quadrume" class="nav-link" data-scroll-target="#ghost-parity-and-the-quadrume">Ghost parity and the quadrume</a></li>
  <li><a href="#unitarity-without-positivity" id="toc-unitarity-without-positivity" class="nav-link" data-scroll-target="#unitarity-without-positivity">Unitarity without positivity</a></li>
  <li><a href="#what-was-actually-verified" id="toc-what-was-actually-verified" class="nav-link" data-scroll-target="#what-was-actually-verified">What was actually verified</a></li>
  <li><a href="#what-this-does-and-does-not-do" id="toc-what-this-does-and-does-not-do" class="nav-link" data-scroll-target="#what-this-does-and-does-not-do">What this does and does not do</a></li>
  <li><a href="#try-it" id="toc-try-it" class="nav-link" data-scroll-target="#try-it">Try it</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Paper and code.</strong> <em>A Projective 2×2 Rotor Architecture for (1+3)D Discrete Spacetime: Holonomies, Ghost Parity, and the Double-Cover Anchor Map.</em> Zenodo preprint, CC BY 4.0, <a href="https://doi.org/10.5281/zenodo.23138782">doi:10.5281/zenodo.23138782</a>. The record includes the PDF, a README, the LaTeX/supplementary archive, and the verification script <code>verify_rotor_model.py</code>.</p>
</div>
</div>
<section id="the-one-paragraph-version" class="level2">
<h2 class="anchored" data-anchor-id="the-one-paragraph-version">The one-paragraph version</h2>
<p>Over a finite field <span class="math inline">\(\mathbb{F}_p\)</span> with <span class="math inline">\(p \equiv 3 \pmod 4\)</span>, you cannot write four-dimensional Lorentzian spacetime as <span class="math inline">\(2\times 2\)</span> matrices over <span class="math inline">\(\mathbb{F}_p\)</span> itself. But if you let the entries live in the quadratic extension <span class="math inline">\(\mathbb{K} = \mathbb{F}_p[i] \cong \mathbb{F}_{p^2}\)</span>, the <strong>Hermitian</strong> <span class="math inline">\(2\times 2\)</span> matrices form a four-dimensional <span class="math inline">\(\mathbb{F}_p\)</span>-space whose determinant <em>is</em> the Lorentz quadratic form. Everything else in the paper follows from that: a compact description of <span class="math inline">\(SO(1,3;\mathbb{F}_p)\)</span>, a formula that reads off a rotation’s generator, a simple explanation of an earlier numerical glitch, and a small model of loop holonomies that you can enumerate exhaustively over <span class="math inline">\(\mathbb{F}_7\)</span>.</p>
</section>
<section id="why-bother-with-finite-fields" class="level2">
<h2 class="anchored" data-anchor-id="why-bother-with-finite-fields">Why bother with finite fields?</h2>
<p>Discrete and finitist approaches to spacetime want geometry that is exact: no limits, no transcendental functions, no floating-point drift. Wildberger’s rational trigonometry and Universal Hyperbolic Geometry replace angles and exponentials with rational operations, and his recent “anchor and cap” construction replaces <span class="math inline">\(\exp\)</span> for <span class="math inline">\(SL(2)\)</span> by a rational map. Working over <span class="math inline">\(\mathbb{F}_p\)</span> pushes that idea to its limit: every statement is a finite, checkable fact.</p>
<p>The cost is that finite fields have no ordering. “Positive” has no meaning. So this is not a claim about physical probabilities. It is an algebraic toy model in which structures from the continuum, such as indefinite inner products, a <span class="math inline">\(\mathbb{Z}_2\)</span> “ghost parity” grading, and holonomies, can be tested exhaustively. The ghost-parity idea is borrowed from recent work of Bateman and Turok on higher-derivative quantum field theory, where a hidden discrete symmetry on a Krein space keeps probabilities well-defined. The finite-field version here is an analogy, not a derivation of their result.</p>
</section>
<section id="the-obstruction-and-why-it-is-not-one" class="level2">
<h2 class="anchored" data-anchor-id="the-obstruction-and-why-it-is-not-one">The obstruction, and why it is not one</h2>
<p>An earlier paper in this series proved a <strong>Witt-index obstruction</strong>. For <span class="math inline">\(p \equiv 3 \pmod 4\)</span> we have <span class="math inline">\(-1\)</span> a non-square, so the form <span class="math inline">\(x_0^2 - x_1^2 - x_2^2 - x_3^2\)</span> has Witt index 1 (elliptic type). The determinant on <span class="math inline">\(M_2(\mathbb{F}_p)\)</span> has Witt index 2 (split). No linear isometry can connect them, so that paper built a <span class="math inline">\(4\times 4\)</span> Clifford-algebra engine instead.</p>
<p>The obstruction only forbids embeddings into <span class="math inline">\(M_2(\mathbb{F}_p)\)</span>. Extend scalars to <span class="math inline">\(\mathbb{K}\)</span> and the picture changes:</p>
<p><span class="math display">\[
X(x) = \begin{pmatrix} x_0 + x_3 &amp; x_1 - i x_2 \\ x_1 + i x_2 &amp; x_0 - x_3 \end{pmatrix},
\qquad \det X(x) = x_0^2 - x_1^2 - x_2^2 - x_3^2 .
\]</span></p>
<p>The matrices <span class="math inline">\(X(x)\)</span> with <span class="math inline">\(x \in \mathbb{F}_p^4\)</span> are exactly the Hermitian ones, and the determinant is <span class="math inline">\(\mathbb{F}_p\)</span>-valued on them. As a quadratic space this is a hyperbolic plane plus an anisotropic plane, so it has Witt index 1, exactly matching the Lorentz form. Nothing is “bypassed” in the sense of breaking Witt’s theorem. We are simply looking at a different quadratic space than the one the theorem excluded. (The earlier paper even remarked that extension of scalars was not ruled out. This paper carries it out.)</p>
</section>
<section id="rotors-all-of-so13mathbbf_p-from-eight-numbers" class="level2">
<h2 class="anchored" data-anchor-id="rotors-all-of-so13mathbbf_p-from-eight-numbers">Rotors: all of <span class="math inline">\(SO(1,3;\mathbb{F}_p)\)</span> from eight numbers</h2>
<p>Write a general element of <span class="math inline">\(M_2(\mathbb{K})\)</span> as <span class="math inline">\(G = xI + \mathbf{z}\cdot\boldsymbol{\sigma}\)</span> with <span class="math inline">\(x = a + ip\)</span> and <span class="math inline">\(\mathbf{z} = \boldsymbol{\kappa} + i\boldsymbol{\rho}\)</span>. Its determinant is <span class="math inline">\(\mathbb{F}_p\)</span>-valued exactly when</p>
<p><span class="math display">\[
ap = \boldsymbol{\kappa}\cdot\boldsymbol{\rho}.
\]</span></p>
<p>That is a quadric in <span class="math inline">\(\mathbb{P}^7(\mathbb{F}_p)\)</span> (a “rotor”). Each non-null rotor acts on Hermitian matrices by <span class="math inline">\(X \mapsto G X G^\dagger / N\)</span>, where <span class="math inline">\(N = a^2 - p^2 - \boldsymbol{\kappa}^2 + \boldsymbol{\rho}^2\)</span>, and this gives a group isomorphism with <span class="math inline">\(SO(1,3;\mathbb{F}_p)\)</span>. The Lorentz matrix has entries that are quadratic polynomials in the eight rotor coordinates divided by the single number <span class="math inline">\(N\)</span>. This isomorphism comes from the companion paper on rational rotations of four-dimensional relativistic space; the present paper builds on it.</p>
<p>Two counts follow, and both were checked by brute force over <span class="math inline">\(\mathbb{F}_7\)</span>:</p>
<ul>
<li><span class="math inline">\(|SO(1,3;\mathbb{F}_7)| = 7^2(7^4 - 1) = 117{,}600\)</span>,</li>
<li>exactly <span class="math inline">\(p^4 + p^2 = 2{,}450\)</span> of them have trace zero. These are the half-turns, which have no anchor (see below).</li>
</ul>
</section>
<section id="reading-off-a-generator-the-anchor-formula" class="level2">
<h2 class="anchored" data-anchor-id="reading-off-a-generator-the-anchor-formula">Reading off a generator: the anchor formula</h2>
<p>The Lie algebra <span class="math inline">\(\mathfrak{so}(1,3)\)</span> is six-dimensional and can be encoded as a vector <span class="math inline">\(\boldsymbol{\zeta} \in \mathbb{K}^3\)</span>, the <strong>anchor</strong>. For any Lorentz transformation <span class="math inline">\(\Lambda\)</span> with <span class="math inline">\(\operatorname{tr}\Lambda \neq 0\)</span>,</p>
<p><span class="math display">\[
A(\Lambda) = \frac{2\,\Lambda_{\mathrm{as}}}{\operatorname{tr}\Lambda},
\qquad
\Lambda_{\mathrm{as}} = \tfrac12\left(\Lambda - \eta\Lambda^{T}\eta\right).
\]</span></p>
<p>No matrix inversion, no logarithm, and it works for rotations with two invariant planes, which was the sticking point for the earlier <span class="math inline">\(4\times 4\)</span> approach. A fair caveat: this is a <em>chart statement</em>. The anchor is the unique parameter for which <span class="math inline">\(\Lambda\)</span> is a “cap” of it, not the generator of a one-parameter subgroup through <span class="math inline">\(\Lambda\)</span>. If your element is already given as a <span class="math inline">\(2\times 2\)</span> spinor <span class="math inline">\(xI + \mathbf{z}\cdot\boldsymbol{\sigma}\)</span>, the anchor is just <span class="math inline">\(\mathbf{z}/x\)</span> and the <span class="math inline">\(4\times 4\)</span> formula adds nothing. The formula earns its keep when you are working in the vector representation.</p>
<p>The caps themselves have a small catch worth knowing. An anchor yields an <span class="math inline">\(\mathbb{F}_p\)</span>-rational Lorentz transformation only when <span class="math inline">\(m^2 = (1-\alpha)^2 + \beta^2\)</span> is a non-zero square in <span class="math inline">\(\mathbb{F}_p\)</span>, where <span class="math inline">\(\zeta\cdot\zeta = \alpha + i\beta\)</span>. Enumerating all <span class="math inline">\(7^6 = 117{,}649\)</span> anchors over <span class="math inline">\(\mathbb{F}_7\)</span>:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Anchors with …</th>
<th>Count</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>rational cap (<span class="math inline">\(m^2\)</span> a non-zero square)</td>
<td>57,575</td>
</tr>
<tr class="even">
<td>no rational cap (<span class="math inline">\(m^2\)</span> a non-square)</td>
<td>57,624</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(m^2 = 0\)</span> (the locus <span class="math inline">\(\zeta\cdot\zeta = 1\)</span>)</td>
<td>2,450</td>
</tr>
</tbody>
</table>
<p>The first number is exactly <span class="math inline">\(\tfrac12(p^6 - p^4 - 2p^2)\)</span>, half the 115,150 rotations with non-zero trace (each anchor gives two caps, <span class="math inline">\(\pm\)</span>). So roughly half of all anchors have no rational cap. That is a genuine finite-field phenomenon.</p>
</section>
<section id="the-anchor-doubling-law-and-the-11-mystery" class="level2">
<h2 class="anchored" data-anchor-id="the-anchor-doubling-law-and-the-11-mystery">The “anchor doubling” law and the 11% mystery</h2>
<p>A previous preprint in the series tried to compose <span class="math inline">\((1+2)\)</span>-dimensional edge anchors using Wildberger’s anchor product, and found that the predicted holonomy trace matched the real <span class="math inline">\(2\times 2\)</span> computation only about 11% of the time. The explanation turns out to be small and structural.</p>
<p>The spinor Cayley map <span class="math inline">\(\mathrm{ca}(\zeta) = (I + \zeta\cdot\sigma)(I - \zeta\cdot\sigma)^{-1}\)</span> lives in <span class="math inline">\(SL(2,\mathbb{K})\)</span>. The Lorentz rotation it induces by conjugation has anchor</p>
<p><span class="math display">\[
\boldsymbol{\zeta}' = \frac{2\boldsymbol{\zeta}}{1 + \boldsymbol{\zeta}\cdot\boldsymbol{\zeta}},
\]</span></p>
<p>so the spin chart and the vector chart are related by a nonlinear <em>doubling</em>, the same phenomenon as angle-doubling in <span class="math inline">\(SU(2)\to SO(3)\)</span>. A neat corollary: <span class="math inline">\(1 - \boldsymbol{\zeta}'\cdot\boldsymbol{\zeta}' = \big((1-\boldsymbol{\zeta}\cdot\boldsymbol{\zeta})/(1+\boldsymbol{\zeta}\cdot\boldsymbol{\zeta})\big)^2\)</span> is a perfect square, so doubled anchors automatically satisfy the descent condition above.</p>
<p>There is a second ingredient. <span class="math inline">\(SL(2) \to SO\)</span> is two-to-one, so the half-trace <span class="math inline">\(T\)</span> is only defined up to sign. The sign-free quantity is <span class="math inline">\(T^2\)</span>, and in <span class="math inline">\((1+2)\)</span> dimensions it satisfies <span class="math inline">\(T^2 = 1 - p\)</span>, where <span class="math inline">\(p\)</span> is the half spread of the rotation. (In <span class="math inline">\((1+3)\)</span> dimensions the analogues are <span class="math inline">\(w^2 = 1 - \pi\)</span> and <span class="math inline">\(N_{\mathbb{K}/\mathbb{F}_p}(w) = 1 - s\)</span>.)</p>
<p>The check is to compose two spinor caps, take the trace of the product, square it, and compare with <span class="math inline">\(1 - p\)</span> computed from the composed doubled anchors. Over primes 7, 11, 13 and 17, every one of about 1.7 million valid test pairs agrees exactly. For contrast, the older, wrong target <span class="math inline">\((1-2p)^2\)</span> agrees only 70%, 38%, 35% and 24% of the time at those primes: accidental agreement that shrinks roughly like <span class="math inline">\(1/p\)</span>.</p>
<p>An honest note on what this shows: it demonstrates that the corrected comparison is exact and that the original failure was of this type. It does not recover the original 11% figure, which came from a different script, so “explains the origin” is the right wording rather than “reproduces the anomaly.”</p>
</section>
<section id="edge-transports-and-holonomy" class="level2">
<h2 class="anchored" data-anchor-id="edge-transports-and-holonomy">Edge transports and holonomy</h2>
<p>To get a connection on a tetrahedron’s vertices, take two non-null points <span class="math inline">\(u, v\)</span> and form the reflection-pair product</p>
<p><span class="math display">\[
X(u)X(v)^{\vee} = B(u,v)\,I + \mathbf{z}_{uv}\cdot\boldsymbol{\sigma}.
\]</span></p>
<p>The edge anchor is <span class="math inline">\(\boldsymbol{\zeta}_{uv} = \mathbf{z}_{uv}/B(u,v)\)</span>, which is unchanged if you rescale <span class="math inline">\(u\)</span> or <span class="math inline">\(v\)</span>, and the transport is its spinor cap:</p>
<p><span class="math display">\[
U_{uv} = (1 - 2s_{uv})\,I + \frac{2B(u,v)}{Q(u)Q(v)}\,\mathbf{z}_{uv}\cdot\boldsymbol{\sigma}
= \frac{\big(X(u)X(v)^\vee\big)^2}{Q(u)Q(v)},
\qquad s_{uv} = 1 - \frac{B(u,v)^2}{Q(u)Q(v)}.
\]</span></p>
<p>Note the square. The <em>unsquared</em> reflection pairs telescope: multiplying them around a closed loop gives a central scalar, which acts as the identity rotation, so the connection is flat. Squaring is a modeling choice that makes the holonomy non-trivial. The paper says so plainly and calls it an ansatz. It rotates by twice the reflection-pair angle and is not a transport that carries <span class="math inline">\([u]\)</span> to <span class="math inline">\([v]\)</span>, so it should not be read as a derivation of curvature.</p>
<p>Over <span class="math inline">\(\mathbb{F}_7\)</span> there are 350 non-null projective points and 68,600 admissible ordered edges. Enumerating every ordered admissible 4-cycle with the first vertex fixed to one representative of each square class (the isometry group acts transitively on each class, an assumption the paper states explicitly), each class gives 4,597,908 cycles. Of these, 9,492 have holonomy <span class="math inline">\(+I\)</span> and 1,680 have <span class="math inline">\(-I\)</span>, so <strong>99.757% have non-trivial holonomy</strong>. A random cross-check (42,972 cycles) gives 0.223% trivial, consistent with the exhaustive 0.243%, and the trace of the holonomy is invariant under cyclic shifts and reversal in every sampled case.</p>
<p>The 0.243% may consist of degenerate (coplanar) vertex configurations. In a random sample of 9,097 non-coplanar cycles, none had trivial holonomy. That is evidence, not proof; an exhaustive non-coplanar count is left to future work.</p>
</section>
<section id="ghost-parity-and-the-quadrume" class="level2">
<h2 class="anchored" data-anchor-id="ghost-parity-and-the-quadrume">Ghost parity and the quadrume</h2>
<p>The <span class="math inline">\(\mathbb{Z}_2\)</span> grading comes from vertex quadrances: <span class="math inline">\(\varepsilon(\gamma) = \prod_i \chi_p(Q(v_i))\)</span>, where <span class="math inline">\(\chi_p\)</span> is the Legendre symbol. The paper realizes this as the spinor-norm character of the open reflection chain <span class="math inline">\(R_\gamma = X_1 X_2^\vee X_3 X_4^\vee\)</span>, whose determinant is <span class="math inline">\(\prod Q(v_i)\)</span>, and ties it to the projective quadrume <span class="math inline">\(\mathcal{V} = \det G_4 / \prod Q(v_i)\)</span> by <span class="math inline">\(\chi_p(\mathcal{V}) = -\varepsilon\)</span>, which comes from <span class="math inline">\(\det\eta = -1\)</span> and <span class="math inline">\(\chi_p(-1) = -1\)</span>.</p>
<p>Two honest remarks. First, this is a consistency identity, close to a definition. <span class="math inline">\(\det R_\gamma = \prod Q(v_i)\)</span> by construction. Second, the grading enters the dynamics only through the mutation rule, which only connects configurations of the same parity. So “ghost sectors decouple” holds by construction here. In Bateman and Turok’s setting, the analogous statement is a nontrivial theorem about an interacting theory. This model does not reproduce that.</p>
</section>
<section id="unitarity-without-positivity" class="level2">
<h2 class="anchored" data-anchor-id="unitarity-without-positivity">Unitarity without positivity</h2>
<p>The dynamics are a Cayley transform <span class="math inline">\(U = (I - iH)(I + iH)^{-1}\)</span> of a symmetric <span class="math inline">\(\mathbb{F}_p\)</span>-valued Hamiltonian <span class="math inline">\(H = -A + gW\)</span>. Because <span class="math inline">\(H\)</span> has entries in <span class="math inline">\(\mathbb{F}_p\)</span>, <span class="math inline">\(U^\dagger U = I\)</span> exactly, and if <span class="math inline">\(H\)</span> commutes with the parity grading <span class="math inline">\(\mathcal{G}\)</span>, so does <span class="math inline">\(U\)</span>. That gives <span class="math inline">\(U^\dagger \mathcal{G} U = \mathcal{G}\)</span> and conserved field-norm weights within each parity sector. These are exact identities in a field with no notion of probability, and they follow quickly from the block structure. The paper defers the actual configuration space, the matrix <span class="math inline">\(A\)</span> and the spectra of <span class="math inline">\(H\)</span> to companion work. Nothing in this paper computes physical dynamics.</p>
</section>
<section id="what-was-actually-verified" class="level2">
<h2 class="anchored" data-anchor-id="what-was-actually-verified">What was actually verified</h2>
<p>All numerical claims are produced by a single script, <code>verify_rotor_model.py</code>, run under Python 3.13 with NumPy 2.1.3. It uses exact finite-field arithmetic, with no floating-point tolerances in the algebra. Its four parts:</p>
<ol type="1">
<li>the <span class="math inline">\((1+2)\)</span> composition test with the corrected target <span class="math inline">\(T^2 = 1 - p\)</span>,</li>
<li>the <span class="math inline">\(\mathbb{F}_7\)</span> holonomy enumeration, the non-coplanar sample, and the <span class="math inline">\(D_4\)</span> check,</li>
<li>the exhaustive anchor census and the group-order counts,</li>
<li>a test that builds <span class="math inline">\(\Lambda_R\)</span> from the actual sandwich <span class="math inline">\(X \mapsto GXG^\dagger/N\)</span> and checks <span class="math inline">\(\Lambda^T\eta\Lambda = \eta\)</span>, <span class="math inline">\(\det\Lambda = 1\)</span>, <span class="math inline">\(\operatorname{tr}\Lambda = 4(a^2+p^2)/N\)</span>, and a characteristic-polynomial coefficient, over 2,499 random rotors.</li>
</ol>
<p>Some of the paper’s identities (for example <span class="math inline">\(\chi_p(\mathcal{V}) = -\varepsilon\)</span>) are tautological once the definitions are fixed, so they are not part of the verification.</p>
</section>
<section id="what-this-does-and-does-not-do" class="level2">
<h2 class="anchored" data-anchor-id="what-this-does-and-does-not-do">What this does and does not do</h2>
<p><strong>It does:</strong> give a compact, exact <span class="math inline">\(2\times 2\)</span> description of the finite-field Lorentz group; explain a specific numerical anomaly as a chart mismatch plus a double-cover sign; provide closed-form edge transports and an exhaustively checked holonomy statistic; and ship code that reproduces every figure in the paper.</p>
<p><strong>It does not:</strong> derive curvature from the holonomy, justify the squared transport beyond calling it an ansatz, reproduce Bateman and Turok’s positivity theorem, or touch continuum limits. The paper lists the quadrume–deficit relation and the large-<span class="math inline">\(p\)</span> limit toward Regge calculus as open problems.</p>
</section>
<section id="try-it" class="level2">
<h2 class="anchored" data-anchor-id="try-it">Try it</h2>
<p>Download the record from <a href="https://doi.org/10.5281/zenodo.23138782">doi:10.5281/zenodo.23138782</a> and run:</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="ex">pip</span> install numpy</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="ex">python</span> verify_rotor_model.py</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>You should see 100.00% agreement in Part 1 at every prime, 99.757% non-trivial holonomy in Part 2, and the counts 57,575 / 57,624 / 2,450 in Part 3. The random-sample figures depend on the NumPy generator, so exact digits in those lines can shift across major NumPy versions. Substitute your own prime in the small functions if you want to explore, but note that the paper’s counts are specific to <span class="math inline">\(p = 7\)</span> (and <span class="math inline">\(p = 7, 11, 13, 17\)</span> for the <span class="math inline">\((1+2)\)</span> test).</p>
</section>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">References</h2>
<ul>
<li>J. D. Coady, <em>A Projective 2×2 Rotor Architecture for (1+3)D Discrete Spacetime</em>, Zenodo (2026), <a href="https://doi.org/10.5281/zenodo.23138782">doi:10.5281/zenodo.23138782</a>.</li>
<li>J. D. Coady, <em>Rational Rotations of Four Dimensional Relativistic Space: Projective Rotors, Anchors and Caps over a General Field</em> (preprint, Oct 2026).</li>
<li>J. D. Coady, <em>A Unified Finitist Indefinite-Hermitian Framework for 3+1D Spacetime</em> (preprint, Sept 2026).</li>
<li>S. Bateman and N. Turok, <em>Escape from Ostrogradsky via Hidden Ghost Parity</em>, arXiv:2607.00096.</li>
<li>N. J. Wildberger, <em>The Anchor to Cap Map Replaces Exp for SL(2)</em> and <em>Rational Rotations of Three Dimensional Relativistic Space</em> (draft manuscripts); <em>Universal Hyperbolic Geometry I: Trigonometry</em>, Geom. Dedicata 163 (2013).</li>
</ul>
<p><em>Code and data were developed with AI assistance (Claude, Anthropic), as disclosed in the paper.</em></p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/jcoady\.github\.io\/blog\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<script src="https://giscus.app/client.js" data-repo="jcoady/blog" data-repo-id="R_kgDOUEMSRA" data-category="General" data-category-id="DIC_kwDOUEMSRM4DEZKl" data-mapping="pathname" data-reactions-enabled="1" data-emit-metadata="0" data-input-position="bottom" data-theme="preferred_color_scheme" data-lang="en" crossorigin="anonymous" async="">
</script>
<input type="hidden" id="giscus-base-theme" value="preferred_color_scheme">
<input type="hidden" id="giscus-alt-theme" value="preferred_color_scheme">
</div> <!-- /content -->




</body></html>